kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-tini
nodes:
- role: control-plane
- role: worker
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "127.0.0.1"
    protocol: TCP